--- #YAML:1.0
name:                ProgressMonitor
version:             0.27
abstract:            a flexible and configurable framework for providing feedback on how a long-running task is proceeding.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    classes:                       0.943
    Term::Size::Win32:             0.207
    Test::More:                    0.64
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Kenneth Olwing <knth@cpan.org>
