--- #YAML:1.0
name:                ProgressMonitor
version:             0.01
abstract:            a flexible and configurable framework and implementations
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Kenneth Olwing <knth@cpan.org>
